#!/bin/bash
# This is an example file for what a post script might look like

# Merge the generated Xdefaults
xrdb -merge $HOME/.cache/kadai/Xdefaults

# Set the image (${1}) as the background
feh --bg-fill ${1}

# Restart the window manager
i3-msg restart